### ISSUE TITLE
Number buttons are triggering secondary functions (e.g. pg_up)

### ISSUE THREAD

**Issue by inhaledesign** [iamkroot/asus-numpad#1] opened 2021-12-07 17:16 UTC
Expected behavior: Touching numbers 1-9 on touch pad will trigger a keypress of t heir respective number.
Actual behavior: Touching numbers 1-9 on touch pad trigger secondary functions (9 will page up, 3 will page down, etc.)
Hardware:  Asus Zenbook UM425Q

Steps:
1. Long press the upper-right icon to enable numberpad
2. Press any number button 0-9

Comments:
Other buttons, such as backspace, '=', and the dimmer button, work as expected. I'm assuming that it's behaving as if numlock is off. Unless I'm blind, there doesn't appear to be a numlock key on the keyboard, so I can't turn it on.

**Comment by iamkroot** [comment] 2021-12-07 18:34
Yeah this happens because we don't actually send "numlock" keypress when the user activates the numpad (we only set the brightness). This is on my todo list (integration with system numlock).
For now, a quick solution would be to find a setting in your DE that specifies the numlock behaviour on startup. For example, KDE allows forcing the numlock to be set to "On" at startup. After that, this driver will work properly.
Or an even simpler solution, use `xdotool` (or some equivalent for wayland) to send a "numlock" keypress.

**Comment by iamkroot** [comment] 2021-12-11 09:57
@inhaledesign Give it a try now- should be fixed in the latest version (v0.3.0)

**Comment by iamkroot** [comment] 2022-01-26 07:28
This has been fixed. Closing due to inactivity.

**Closed as completed by iamkroot** 2022-01-26 07:28 UTC

**Comment by franckgaga** [comment] 2022-01-26 14:12
I confirm that the problem is fixed in the latest version, thanks !
